name: Condition Demo

on: workflow_dispatch

jobs:
    build:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'

      steps:
      - name: Step 1
        run: echo "Hello"

      - name: Step 2
        if: success()
        run: echo "Runs only if step 1 succeeded"

