name: Env Variables Demo

on: workflow_dispatch

env:
  GLOBAL_ENV: "global-value"

jobs:
  demo:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Print all environment variables
        env:
          API_URL: ${{vars.API_URL}}
          DB_PASS: ${{secrets.DB_PASSWORD}}
        run: |
          echo "API URL: $API_URL"
          echo "DB password lenght: ${#DB_PASS}"
          echo "DB password: $DB_PASS"
      - name: write secret to file
        run: |
          echo "DB password: $DB_PASS" > db_password.txt
        env:
          DB_PASS: ${{secrets.DB_PASSWORD}}
      - name: Read the file
        run: cat db_password.txt

