name: Explore Github components

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build jobs
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Display runner info
        run: |
          echo "Runner os: $RUNNER_OS"
          echo "Runner Arch: $RUNNER_ARCH"
          echo "workspace: $GITHUB_WORKSPACE"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "SHA: $GITHUB_SHA"